services:
- docker
install:
- pip install --user awscli
before_script:
- echo "no before scripts actions"
script:
- docker --version
- docker build -t udagram-reverse-proxy .
- docker tag udagram-reverse-proxy:latest 998443328643.dkr.ecr.us-east-1.amazonaws.com/udagram-reverse-proxy:latest
after_success:
- aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin
  998443328643.dkr.ecr.us-east-1.amazonaws.com
- docker push 998443328643.dkr.ecr.us-east-1.amazonaws.com/udagram-reverse-proxy:latest
env:
  global:
  - secure: Kc0zN2h4yfsnLVWpjo5pnn2kiOK86haSZVip1Gy4KdlolwiMhne45t3G4dD2Rm4w0pmVmu8Yn2H/+wQ8hbPpNnAKAVwg+AuGKLIfOZRcxkQhRUvSem9+ejzT0cxrGjVgNcR/KmD86FepgiE7GHnJRb980BVo0AXqXLO13Myj6ujCvi+jn1qZYBOUdKbz3I+cUjVM58h8Hikm/XrAHmZtg3cAfEPdNOZ/jlfyzSeJ63hhwZqHsKbjpOhD8hv++2i+sCTYw0/6LJ9HnGCAnnioT9IcDaYLaPcllnDaqrYMTToipK0ePYQH8GzynIzwFVnZdDK5QZETTw5Le1yEqGChUS9uMlNh4n9nZ+4kd3HrHsetshTd0AqV3ajf8ImkKF6PXEoKpEA50bGnq/GPn6zxhQFHshkJ+5xORULHPYJ39/Cx9Q5KlpAZnsTomdvuW3WUSIjlalkKxUPGCB00U0AkGtdMnl2LYW4ZlVYmdwpTsunKR0DuTZxn0LgsH2xEOxm4ImVmW7jPJwMqIPax3wjUYvKqhLkSaHh0K9lndOSydpbmWcGx2wGVyAyI0xhgcVOThVAF1Jux1fZyDzNxm91OexwAsf/5ShcHm+ga/BklI1IaNubAy5/14QroJGxPxbEx8ONpscU7u5hyCq27/7PD4j0XS+Pm89a1JURvYeAr6Dk=
  - secure: pks80AP5fGZT08z6QQxyLlCbxY9WwCMej+xhuLq53o3hI/3+io2F/zgmPGOIWs3IlN6l+tK0DmuIAorxRbEEWfBGZKA6y1UzFqUYE1HSbzd0QFxIjcnEfMyP7ctav7ihVBr8dtBpbbI1U04SnmUIx4Io4OfvwN1Tl2pXlwNLu7l0xEs2rvZBz/+b4k5OdivnK0pIIWogfl/YbofSmbaH6QfB8uWaWRB0dJAWqgtlMMBphNoZVJi4r7aDHb9YZ/Z/Q+7oC1KOiDVJcTVjQjAzjcMXRRZRBqQR4L3EepZUvXe5JS7/M9VAzXPER2Oh2RdzqgxwLbQoBxmGO7tsRBN6bSI1vQWv1TY1PkqmFEtmJGDaPDyZs8Rc9oJdXxT4QscgTCYrbz1WJ86fnJWz4qoRRlzIMivG84XnqkQ4QHhfrzLAkWZWC0TMfFsWAzEBVI0RErQ5VQlAEpIA4QCl0pxOJ7AXhrH5EvLqqXmHmbZ4H9JrTeqq1u8JT89E+hR8sNm1F0v1FVRLUpyGUydtgd2ubcoracOEiBt6c5Q6k1LH+tbjqMWVzGWz8OwYeWzvOI7f0NJ5LbGV4gRIH92S98TJ5FKwqMca91cdxMh3pzmmKG5ceGzN3h+Oh36bTLYpPRPfoqiTCArzvLdiqoI0T5Y5ku203X0/XxFl+MAEbfWCMSo=
