apiVersion: v1
kind: Service
metadata:
  name: udagram-reverse-proxy
spec:
  type: LoadBalancer
  selector:
    app: udagram-reverse-proxy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
